#Limpieza de DR1TOT_H

In [1]:
# from google.colab import drive
# from google.colab import files
# drive.mount('/content/drive')
import pandas as pd
import numpy as np

dr1 = pd.read_csv("../data/interim/dr1tot_h_columnas.csv")
# dr1 = pd.read_csv("/content/drive/MyDrive/kokoa-analisis-salud-mental-codespace-refactored-xylophone-g4566pggg7r9hw9jv/data/interim/dr1tot_h_columnas.csv")
dr1.head()

,SEQN,DRQSDIET,DRQSDT1,DRQSDT2,DRQSDT3,DRQSDT4,DRQSDT5,DRQSDT6,DRQSDT7,DRQSDT8,DRQSDT9,DRQSDT10,DRQSDT11,DRQSDT12,DRQSDT91
0,73557.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,73558.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,73559.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN
3,73560.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,73561.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0

In [2]:
DR1_COLS = dr1.columns.tolist()
dr1 = dr1[DR1_COLS].copy()
dr1.head()

,SEQN,DRQSDIET,DRQSDT1,DRQSDT2,DRQSDT3,DRQSDT4,DRQSDT5,DRQSDT6,DRQSDT7,DRQSDT8,DRQSDT9,DRQSDT10,DRQSDT11,DRQSDT12,DRQSDT91
0,73557.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,73558.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,73559.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN
3,73560.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,73561.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0

In [3]:
codigos_invalidos = [7, 9, 77, 99, 777, 999, 7777, 9999]
dr1.replace(codigos_invalidos, np.nan, inplace=True)

dr1.isna().sum()

SEQN           0
DRQSDIET    1076
DRQSDT1     9290
DRQSDT2     9682
DRQSDT3     9692
DRQSDT4     9776
DRQSDT5     9813
DRQSDT6     9809
DRQSDT7     9813
DRQSDT8     9779
DRQSDT9     9813
DRQSDT10    9791
DRQSDT11    9782
DRQSDT12    9805
DRQSDT91    9738
dtype: int64

In [4]:
for col in dr1.columns:
    if col != "SEQN":
        dr1[col] = pd.to_numeric(dr1[col], errors="coerce")

dr1.dtypes

SEQN        float64
DRQSDIET    float64
DRQSDT1     float64
DRQSDT2     float64
DRQSDT3     float64
DRQSDT4     float64
DRQSDT5     float64
DRQSDT6     float64
DRQSDT7     float64
DRQSDT8     float64
DRQSDT9     float64
DRQSDT10    float64
DRQSDT11    float64
DRQSDT12    float64
DRQSDT91    float64
dtype: object

In [5]:
dr1.describe()

,SEQN,DRQSDIET,DRQSDT1,DRQSDT2,DRQSDT3,DRQSDT4,DRQSDT5,DRQSDT6,DRQSDT7,DRQSDT8,DRQSDT9,DRQSDT10,DRQSDT11,DRQSDT12,DRQSDT91
count,9813.000000,8737.000000,523.0,131.0,121.0,37.0,0.0,4.0,0.0,34.0,0.0,22.0,31.0,8.0,75.0
mean,78644.559971,1.881767,1.0,2.0,3.0,4.0,NaN,6.0,NaN,8.0,NaN,10.0,11.0,12.0,91.0
std,2938.592266,0.322902,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0
min,73557.000000,1.000000,1.0,2.0,3.0,4.0,NaN,6.0,NaN,8.0,NaN,10.0,11.0,12.0,91.0
25%,76092.000000,2.000000,1.0,2.0,3.0,4.0,NaN,6.0,NaN,8.0,NaN,10.0,11.0,12.0,91.0
50%,78643.000000,2.000000,1.0,2.0,3.0,4.0,NaN,6.0,NaN,8.0,NaN,10.0,11.0,12.0,91.0
75%,81191.000000,2.000000,1.0,2.0,3.0,4.0,NaN,6.0,NaN,8.0,NaN,10.0,11.0,12.0,91.0
max,83731.000000,2.000000,1.0,2.0,3.0,4.0,NaN,6.0,NaN,8.0,NaN,10.0,11.0,12.0,91.0

In [6]:
for col in dr1.columns:
    if col != "SEQN":
        dr1[col] = dr1[col].fillna(0)

dr1.isna().sum()

SEQN        0
DRQSDIET    0
DRQSDT1     0
DRQSDT2     0
DRQSDT3     0
DRQSDT4     0
DRQSDT5     0
DRQSDT6     0
DRQSDT7     0
DRQSDT8     0
DRQSDT9     0
DRQSDT10    0
DRQSDT11    0
DRQSDT12    0
DRQSDT91    0
dtype: int64

In [7]:
conteo_no_cero = ((dr1 != 0)).sum()

In [8]:
conteo_no_cero

SEQN        9813
DRQSDIET    8737
DRQSDT1      523
DRQSDT2      131
DRQSDT3      121
DRQSDT4       37
DRQSDT5        0
DRQSDT6        4
DRQSDT7        0
DRQSDT8       34
DRQSDT9        0
DRQSDT10      22
DRQSDT11      31
DRQSDT12       8
DRQSDT91      75
dtype: int64

In [9]:
dr1.to_csv('../data/processed/dr1tot_limpio.csv')
print("DR1TOT limpio guardado")

DR1TOT limpio guardado

#Limpieza de DUQ_H

In [10]:
duq = pd.read_csv('../data/interim/duq_h_columnas.csv')
duq.head()

,SEQN,DUQ200,DUQ230,DUQ210,DUQ240,DUQ280,DUQ320,DUQ360,DUQ370,DUQ410,DUQ430
0,73557.0,NaN,NaN,NaN,7.0,NaN,NaN,NaN,2.0,NaN,NaN
1,73558.0,1.0,20.0,18.0,1.0,NaN,NaN,NaN,2.0,NaN,2.0
2,73562.0,1.0,NaN,16.0,2.0,NaN,NaN,NaN,2.0,NaN,2.0
3,73564.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0,NaN,NaN
4,73566.0,1.0,NaN,21.0,2.0,NaN,NaN,NaN,2.0,NaN,2.0

In [11]:
duq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5057 entries, 0 to 5056
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SEQN    5057 non-null   float64
 1   DUQ200  3701 non-null   float64
 2   DUQ230  570 non-null    float64
 3   DUQ210  1991 non-null   float64
 4   DUQ240  4540 non-null   float64
 5   DUQ280  45 non-null     float64
 6   DUQ320  8 non-null      float64
 7   DUQ360  30 non-null     float64
 8   DUQ370  4539 non-null   float64
 9   DUQ410  105 non-null    float64
 10  DUQ430  2014 non-null   float64
dtypes: float64(11)
memory usage: 434.7 KB

In [12]:
DUQ_COLS = duq.columns.tolist()
duq = duq[DUQ_COLS].copy()
duq.head()

,SEQN,DUQ200,DUQ230,DUQ210,DUQ240,DUQ280,DUQ320,DUQ360,DUQ370,DUQ410,DUQ430
0,73557.0,NaN,NaN,NaN,7.0,NaN,NaN,NaN,2.0,NaN,NaN
1,73558.0,1.0,20.0,18.0,1.0,NaN,NaN,NaN,2.0,NaN,2.0
2,73562.0,1.0,NaN,16.0,2.0,NaN,NaN,NaN,2.0,NaN,2.0
3,73564.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0,NaN,NaN
4,73566.0,1.0,NaN,21.0,2.0,NaN,NaN,NaN,2.0,NaN,2.0

In [13]:
codigos_invalidos = [7, 9, 77, 99, 777, 999]
duq.replace(codigos_invalidos, np.nan, inplace=True)

duq.isna().sum()

SEQN         0
DUQ200    1367
DUQ230    4503
DUQ210    3079
DUQ240     534
DUQ280    5014
DUQ320    5049
DUQ360    5027
DUQ370     522
DUQ410    4953
DUQ430    3044
dtype: int64

In [14]:
for col in duq.columns:
    if col != "SEQN":
        duq[col] = pd.to_numeric(duq[col], errors="coerce")

duq.dtypes

SEQN      float64
DUQ200    float64
DUQ230    float64
DUQ210    float64
DUQ240    float64
DUQ280    float64
DUQ320    float64
DUQ360    float64
DUQ370    float64
DUQ410    float64
DUQ430    float64
dtype: object

In [15]:
for col in duq.columns:
    if col != "SEQN":
        if duq[col].dropna().nunique() == 2:
            duq[col] = duq[col].fillna(duq[col].mode()[0])
        else:
            duq[col] = duq[col].fillna(duq[col].median())

duq.isna().sum()

SEQN      0
DUQ200    0
DUQ230    0
DUQ210    0
DUQ240    0
DUQ280    0
DUQ320    0
DUQ360    0
DUQ370    0
DUQ410    0
DUQ430    0
dtype: int64

In [16]:
duq.to_csv('../data/processed/duq_limpio.csv')
print("DUQ limpio guardado")

DUQ limpio guardado

#Limpieza de DBQ_H

In [17]:
dbq = pd.read_csv("../data/interim/dbq_h_columnas.csv")
df_demo = pd.read_csv("../data/interim/demo_h_columnas.csv")
df_edad = df_demo[['SEQN', 'RIDAGEYR']].copy()
dbq = dbq.merge(df_edad,on='SEQN',how='inner')
dbq = dbq[dbq['RIDAGEYR']>=18]
dbq.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6113 entries, 0 to 10172
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      6113 non-null   float64
 1   DBQ700    6113 non-null   float64
 2   DBD895    6113 non-null   float64
 3   DBD900    4690 non-null   float64
 4   DBD905    6099 non-null   float64
 5   DBD910    6102 non-null   float64
 6   RIDAGEYR  6113 non-null   float64
dtypes: float64(7)
memory usage: 382.1 KB

In [18]:
# 1. Redondear la columna DBD895 para eliminar los errores de coma flotante
# Redondeamos y la convertimos temporalmente/permanentemente para que el 5.39e-79 sea 0
dbq['DBD895'] = dbq['DBD895'].round()


# si no comiste fuera de casa, no tiene sentido preguntar dbd900
dbq['DBD900'] = np.where(dbq['DBD895'] == 0, 0, dbq['DBD900'])
dbq['DBD900'] = np.where(dbq['DBD895'] == 7777, 7777, dbq['DBD900'])
dbq['DBD900'] = np.where(dbq['DBD895'] == 9999, 9999, dbq['DBD900'])

# 3. Comprobamos los nulos
print(dbq.info())

<class 'pandas.core.frame.DataFrame'>
Index: 6113 entries, 0 to 10172
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      6113 non-null   float64
 1   DBQ700    6113 non-null   float64
 2   DBD895    6113 non-null   float64
 3   DBD900    6113 non-null   float64
 4   DBD905    6099 non-null   float64
 5   DBD910    6102 non-null   float64
 6   RIDAGEYR  6113 non-null   float64
dtypes: float64(7)
memory usage: 382.1 KB
None

In [19]:
import pandas as pd
import numpy as np


# 2. Arreglar nulos en DBD905 y DBD910
# Tienes muy pocos nulos aquí (14 en DBD905 y 11 en DBD910 de un total de 6113 filas).
# Rellenarlos con la mediana
median_905 = dbq['DBD905'].median()
median_910 = dbq['DBD910'].median()
dbq['DBD905'] = dbq['DBD905'].fillna(median_905)
dbq['DBD910'] = dbq['DBD910'].fillna(median_910)

# 3. Verificación
print(dbq.info())

<class 'pandas.core.frame.DataFrame'>
Index: 6113 entries, 0 to 10172
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      6113 non-null   float64
 1   DBQ700    6113 non-null   float64
 2   DBD895    6113 non-null   float64
 3   DBD900    6113 non-null   float64
 4   DBD905    6113 non-null   float64
 5   DBD910    6113 non-null   float64
 6   RIDAGEYR  6113 non-null   float64
dtypes: float64(7)
memory usage: 382.1 KB
None

In [20]:
dbq.to_csv('../data/processed/dbq_limpio.csv')
dbq.drop(columns='RIDAGEYR')
print("DBQ limpio guardado")

DBQ limpio guardado

#Limpieza de BMX_H

In [21]:
bmx = pd.read_csv('../data/interim/bmx_h_columnas.csv')
bmx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9813 entries, 0 to 9812
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      9813 non-null   float64
 1   BMXBMI    9055 non-null   float64
 2   BMXWAIST  8661 non-null   float64
dtypes: float64(3)
memory usage: 230.1 KB

In [22]:
BMX_COLS = bmx.columns.tolist()
bmx = bmx[BMX_COLS].copy()
bmx.head()

      SEQN  BMXBMI  BMXWAIST
0  73557.0    26.7     100.0
1  73558.0    28.6     107.6
2  73559.0    28.9     109.2
3  73560.0    17.1      61.0
4  73561.0    19.7       NaN

In [23]:
bmx.replace([7, 9, 77, 99], np.nan, inplace=True)
bmx.isna().sum()

SEQN           0
BMXBMI       758
BMXWAIST    1177
dtype: int64

In [24]:
for col in bmx.columns:
    if col != "SEQN":
        bmx[col] = pd.to_numeric(bmx[col], errors="coerce")

bmx.dtypes

SEQN        float64
BMXBMI      float64
BMXWAIST    float64
dtype: object

In [25]:
bmx.describe()

               SEQN       BMXBMI     BMXWAIST
count   9813.000000  9055.000000  8636.000000
mean   78644.559971    25.678244    87.271214
std     2938.592266     7.955137    22.567461
min    73557.000000    12.100000    40.200000
25%    76092.000000    19.700000    71.100000
50%    78643.000000    24.700000    87.800000
75%    81191.000000    30.200000   102.800000
max    83731.000000    82.900000   177.900000

In [26]:
for col in bmx.columns:
    if col != "SEQN":
        bmx[col] = bmx[col].fillna(bmx[col].median())

bmx.isna().sum()

SEQN        0
BMXBMI      0
BMXWAIST    0
dtype: int64

In [28]:
bmx.to_csv("../data/processed/bmx_limpio.csv",index=False)
print("BMX limpio guardado")

BMX limpio guardado